# Site settings
title:       EE's Blog   ／  Never Stop Learning  
email:       xiaoquan.vip@gmail.com 
author:      John Otander
description: "EE's Blog,focused on python & web!"
baseurl:     ""
url:         "http://pqx.ee/"

#Duoshuo short Name
duoshuo: blog-maxee

#Baidu analytics
baidu_analyze: 3908cbb144cf558ba6a823230d653fc1 

# Google analytics
google_analytics:

# Optional features
animated:           false
show_related_posts: false
show_post_footers:  false

# Social icons
show_social_icons: false
github_username: ee0703
twitter_username: maxee0703
google_plus_id:
linkedin_username:
bitcoin_url:
paypal_url:
flattr_button:

# Build settings
markdown:     kramdown
permalink:    pretty 
paginate:     3
sass:
  compressed: true
#jekyll sitemap
gems:
  - jekyll-sitemap
